version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg-email-agent-compose
    environment:
      # These values are read automatically from the .env file
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: python-email-agent
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      # These values are also read automatically from the .env file
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db # We keep this hardcoded, as it's specific to the Docker network
      - DB_PORT=${DB_PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: on-failure

volumes:
  postgres_data: