version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg-email-agent-compose
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=email_agent
    ports:
      - "5432:5432" # Expose port 5432 to the host machine for external connections
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

  # The Python Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: python-email-agent
    depends_on:
      - db # This service will not start until the 'db' service is ready
    volumes:
      - .:/app # Mount the current directory into the container's /app directory
    environment:
      # Pass database connection details as environment variables
      - DB_NAME=email_agent
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db # IMPORTANT: The hostname is the service name ('db')
      - DB_PORT=5432
    # Keep the container running even if the script exits, useful for debugging
    restart: on-failure

volumes:
  postgres_data: # Define the named volume for data persistence